# Environment Setup

In [1]:
import pandas as pd
import requests
import os

# Download OWID Datasets

In [2]:
def download_csv(url, file_name, folder = "F:\\DATA SCIENCE\\Projects\\Global Literacy & Educational Trends\\data\\raw"):
    os.makedirs(folder, exist_ok = True)

    headers = {"User-Agent": "Mozilla/5.0"}
    response = requests.get(url, headers = headers)
    response.raise_for_status()

    save_path = os.path.join(folder, f"{file_name}.csv")

    with open(save_path, "w", encoding = "utf-8") as f:
        f.write(response.text)

    print(f"Saved to {save_path}")

## Adult Literacy Rate

In [7]:
download_csv("https://ourworldindata.org/grapher/literacy-rate-adults.csv?v=1&csvType=full&useColumnShortNames=true", "adult_literacy_rate")

Saved to F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\data\raw\adult_literacy_rate.csv

In [12]:
df_alr = pd.read_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\data\raw\adult_literacy_rate.csv")
df_alr.head()

,entity,code,year,adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99
0,Afghanistan,AFG,1979,18.00000
1,Afghanistan,AFG,2011,31.00000
2,Afghanistan,AFG,2015,33.75384
3,Afghanistan,AFG,2021,37.00000
4,Albania,ALB,2001,99.00000

In [9]:
df_alr.shape

(1725, 4)

In [10]:
df_alr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1725 entries, 0 to 1724
Data columns (total 4 columns):
 #   Column                                                                     Non-Null Count  Dtype
---  ------                                                                     --------------  -----
 0   entity                                                                     1725 non-null   object
 1   code                                                                       996 non-null    object
 2   year                                                                       1725 non-null   int64
 3   adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99  1725 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 54.0+ KB

## Youth Literacy Rate (Male, Female)

In [11]:
download_csv("https://ourworldindata.org/grapher/literacy-rate-of-young-men-and-women.csv?v=1&csvType=full&useColumnShortNames=true", "youth_literacy_rate")

Saved to F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\data\raw\youth_literacy_rate.csv

In [13]:
df_ylr = pd.read_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\data\raw\youth_literacy_rate.csv")
df_ylr.head()

,entity,code,year,youth_literacy_rate__population_15_24_years__male__pct__lr_ag15t24_m,youth_literacy_rate__population_15_24_years__female__pct__lr_ag15t24_f,owid_region
0,Afghanistan,AFG,1979,46.00000,11.00000,Asia
1,Afghanistan,AFG,2011,62.00000,32.00000,Asia
2,Afghanistan,AFG,2015,57.73505,25.48416,Asia
3,Afghanistan,AFG,2021,71.00000,42.00000,Asia
4,Afghanistan,AFG,2022,83.40000,44.17171,Asia

In [13]:
df_ylr.shape

(2002, 6)

In [14]:
df_ylr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2002 entries, 0 to 2001
Data columns (total 6 columns):
 #   Column                                                                  Non-Null Count  Dtype
---  ------                                                                  --------------  -----
 0   entity                                                                  2002 non-null   object
 1   code                                                                    1260 non-null   object
 2   year                                                                    2002 non-null   int64
 3   youth_literacy_rate__population_15_24_years__male__pct__lr_ag15t24_m    1925 non-null   float64
 4   youth_literacy_rate__population_15_24_years__female__pct__lr_ag15t24_f  2002 non-null   float64
 5   owid_region                                                             1211 non-null   object
dtypes: float64(2), int64(1), object(3)
memory usage: 94.0+ KB

## Illiterate Population (Total, Male, Female)

In [15]:
download_csv("https://ourworldindata.org/grapher/literate-and-illiterate-world-population.csv?v=1&csvType=full&useColumnShortNames=true", "illiterate_population")

Saved to F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\data\raw\illiterate_population.csv

In [14]:
df_ip = pd.read_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\data\raw\illiterate_population.csv")
df_ip.head()

        entity code  year  illiteracy_rate  literacy_rate
0  Afghanistan  AFG  1950        97.000000        3.00000
1  Afghanistan  AFG  1979        82.000000       18.00000
2  Afghanistan  AFG  2011        69.000000       31.00000
3  Afghanistan  AFG  2015        66.246155       33.75384
4  Afghanistan  AFG  2021        63.000000       37.00000

In [18]:
df_ip.shape

(2059, 5)

In [19]:
df_ip.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2059 entries, 0 to 2058
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   entity           2059 non-null   object
 1   code             1326 non-null   object
 2   year             2059 non-null   int64
 3   illiteracy_rate  2059 non-null   float64
 4   literacy_rate    2059 non-null   float64
dtypes: float64(2), int64(1), object(2)
memory usage: 80.6+ KB

## GDP per Capita

In [3]:
download_csv("https://ourworldindata.org/grapher/gdp-per-capita-worldbank.csv?v=1&csvType=full&useColumnShortNames=true", "gdp_capita")

Saved to F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\data\raw\gdp_capita.csv

In [15]:
df_gc = pd.read_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\data\raw\gdp_capita.csv")
df_gc.head()

        entity code  year  ny_gdp_pcap_pp_kd owid_region
0  Afghanistan  AFG  2000          1617.8264        Asia
1  Afghanistan  AFG  2001          1454.1108        Asia
2  Afghanistan  AFG  2002          1774.3087        Asia
3  Afghanistan  AFG  2003          1815.9282        Asia
4  Afghanistan  AFG  2004          1776.9182        Asia

In [5]:
df_gc.shape

(7240, 5)

In [6]:
df_gc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7240 entries, 0 to 7239
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   entity             7240 non-null   object
 1   code               7240 non-null   object
 2   year               7240 non-null   int64
 3   ny_gdp_pcap_pp_kd  7240 non-null   float64
 4   owid_region        6785 non-null   object
dtypes: float64(1), int64(1), object(3)
memory usage: 282.9+ KB

## Avg. Years of Schooling

In [7]:
download_csv("https://ourworldindata.org/grapher/literacy-rates-vs-average-years-of-schooling.csv?v=1&csvType=full&useColumnShortNames=true", "avg_yrs_schooling")

Saved to F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\data\raw\avg_yrs_schooling.csv

In [16]:
df_ays = pd.read_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\data\raw\avg_yrs_schooling.csv")
df_ays.head()

,entity,code,year,literacy_rate,mf_youth_and_adults__15_64_years__average_years_of_education,population_historical,owid_region
0,Afghanistan,AFG,1870,NaN,0.01,4101170.0,Asia
1,Afghanistan,AFG,1875,NaN,0.01,4193635.0,Asia
2,Afghanistan,AFG,1880,NaN,0.01,4288021.0,Asia
3,Afghanistan,AFG,1885,NaN,0.01,4384343.0,Asia
4,Afghanistan,AFG,1890,NaN,0.01,4482635.0,Asia

In [9]:
df_ays.shape

(5365, 7)

In [10]:
df_ays.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5365 entries, 0 to 5364
Data columns (total 7 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   entity                                                        5365 non-null   object
 1   code                                                          4475 non-null   object
 2   year                                                          5365 non-null   int64
 3   literacy_rate                                                 2000 non-null   float64
 4   mf_youth_and_adults__15_64_years__average_years_of_education  3668 non-null   float64
 5   population_historical                                         4760 non-null   float64
 6   owid_region                                                   4472 non-null   object
dtypes: float64(3), int64(1), object(3)
memory usage: 293.5+ KB

# Initial Structural Audit

## Unique Countries Count

In [18]:
print(df_alr["entity"].unique())
print(df_alr["entity"].nunique())

['Afghanistan' 'Albania' 'Algeria' 'American Samoa' 'Angola' 'Anguilla'
 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba' 'Azerbaijan'
 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus' 'Belize' 'Benin' 'Bhutan'
 'Bolivia' 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'Brunei'
 'Bulgaria' 'Burkina Faso' 'Burundi' 'Cambodia' 'Cameroon' 'Cape Verde'
 'Cayman Islands' 'Central African Republic'
 'Central and Southern Asia (SDG)' 'Chad' 'Chile' 'China' 'Colombia'
 'Comoros' 'Congo' 'Costa Rica' "Cote d'Ivoire" 'Croatia' 'Cuba' 'Cyprus'
 'Democratic Republic of Congo' 'Dominican Republic'
 'East Asia and Pacific (WB)' 'East Timor'
 'Eastern and South-Eastern Asia (SDG)' 'Ecuador' 'Egypt' 'El Salvador'
 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia'
 'Europe and Central Asia (WB)' 'Europe and Northern America (SDG)'
 'French Guiana' 'Gabon' 'Gambia' 'Georgia' 'Ghana' 'Greece' 'Grenada'
 'Guadeloupe' 'Guam' 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti'
 'Honduras' 'Hungary' 'India' 'Indonesia' 'Iran' 'Iraq' 'Israel' 'Italy'
 'Jamaica' 'Jordan' 'Kazakhstan' 'Kenya' 'Kiribati' 'Kuwait' 'Kyrgyzstan'
 'Laos' 'Latin America and Caribbean (WB)'
 'Latin America and the Caribbean (SDG)' 'Latvia' 'Lebanon' 'Lesotho'
 'Liberia' 'Libya' 'Lithuania' 'Low-income countries'
 'Lower-middle-income countries' 'Macao' 'Madagascar' 'Malawi' 'Malaysia'
 'Maldives' 'Mali' 'Malta' 'Marshall Islands' 'Martinique' 'Mauritania'
 'Mauritius' 'Mexico' 'Middle East and North Africa (WB)'
 'Middle-income countries' 'Moldova' 'Mongolia' 'Montenegro' 'Morocco'
 'Mozambique' 'Myanmar' 'Namibia' 'Nauru' 'Nepal' 'New Caledonia'
 'Nicaragua' 'Niger' 'Nigeria' 'North America (WB)' 'North Korea'
 'North Macedonia' 'Northern Africa and Western Asia (SDG)'
 'Oceania (excluding Australia and New Zealand) (SDG)' 'Oman' 'Pakistan'
 'Palau' 'Palestine' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru'
 'Philippines' 'Poland' 'Portugal' 'Puerto Rico' 'Qatar' 'Reunion'
 'Romania' 'Russia' 'Rwanda' 'Saint Helena' 'Saint Pierre and Miquelon'
 'Saint Vincent and the Grenadines' 'Samoa' 'San Marino'
 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia' 'Seychelles'
 'Sierra Leone' 'Singapore' 'Slovenia' 'Solomon Islands' 'Somalia'
 'South Africa' 'South Asia (WB)' 'South Korea' 'South Sudan' 'Spain'
 'Sri Lanka' 'Sub-Saharan Africa (SDG)' 'Sub-Saharan Africa (WB)' 'Sudan'
 'Suriname' 'Syria' 'Tajikistan' 'Tanzania' 'Thailand' 'Togo' 'Tonga'
 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Turkmenistan' 'Uganda'
 'Ukraine' 'United Arab Emirates' 'Upper-middle-income countries'
 'Uruguay' 'Uzbekistan' 'Vanuatu' 'Venezuela' 'Vietnam' 'World' 'Yemen'
 'Zambia' 'Zimbabwe']
195

In [19]:
print(df_ylr["entity"].unique())
print(df_ylr["entity"].nunique())

['Afghanistan' 'Albania' 'Algeria' 'American Samoa' 'Angola' 'Anguilla'
 'Argentina' 'Armenia' 'Aruba' 'Azerbaijan' 'Bahrain' 'Bangladesh'
 'Barbados' 'Belarus' 'Belize' 'Benin' 'Bhutan' 'Bolivia'
 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'Brunei' 'Bulgaria'
 'Burkina Faso' 'Burundi' 'Cambodia' 'Cameroon' 'Cape Verde'
 'Cayman Islands' 'Central African Republic'
 'Central and Southern Asia (SDG)' 'Chad' 'Chile' 'China' 'Colombia'
 'Comoros' 'Congo' 'Costa Rica' "Cote d'Ivoire" 'Croatia' 'Cuba' 'Cyprus'
 'Democratic Republic of Congo' 'Djibouti' 'Dominican Republic'
 'East Asia and Pacific (WB)' 'East Timor'
 'Eastern and South-Eastern Asia (SDG)' 'Ecuador' 'Egypt' 'El Salvador'
 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia'
 'Europe and Central Asia (WB)' 'Europe and Northern America (SDG)' 'Fiji'
 'Gabon' 'Gambia' 'Georgia' 'Ghana' 'Greece' 'Grenada' 'Guadeloupe' 'Guam'
 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti'
 'High-income countries' 'Honduras' 'Hungary' 'India' 'Indonesia' 'Iran'
 'Iraq' 'Israel' 'Italy' 'Jamaica' 'Jordan' 'Kazakhstan' 'Kenya'
 'Kiribati' 'Kuwait' 'Kyrgyzstan' 'Laos'
 'Latin America and Caribbean (WB)'
 'Latin America and the Caribbean (SDG)' 'Latvia' 'Lebanon' 'Lesotho'
 'Liberia' 'Libya' 'Lithuania' 'Low-income countries'
 'Lower-middle-income countries' 'Macao' 'Madagascar' 'Malawi' 'Malaysia'
 'Maldives' 'Mali' 'Malta' 'Marshall Islands' 'Martinique' 'Mauritania'
 'Mauritius' 'Mexico' 'Middle East and North Africa (WB)'
 'Middle-income countries' 'Moldova' 'Mongolia' 'Montenegro' 'Morocco'
 'Mozambique' 'Myanmar' 'Namibia' 'Nepal' 'New Caledonia' 'Nicaragua'
 'Niger' 'Nigeria' 'North America (WB)' 'North Korea' 'North Macedonia'
 'Northern Africa and Western Asia (SDG)'
 'Oceania (excluding Australia and New Zealand) (SDG)' 'Oman' 'Pakistan'
 'Palau' 'Palestine' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru'
 'Philippines' 'Poland' 'Portugal' 'Puerto Rico' 'Qatar' 'Reunion'
 'Romania' 'Russia' 'Rwanda' 'Saint Helena' 'Saint Lucia'
 'Saint Pierre and Miquelon' 'Saint Vincent and the Grenadines' 'Samoa'
 'San Marino' 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia'
 'Seychelles' 'Sierra Leone' 'Singapore' 'Slovenia' 'Somalia'
 'South Africa' 'South Asia (WB)' 'South Korea' 'South Sudan' 'Spain'
 'Sri Lanka' 'Sub-Saharan Africa (SDG)' 'Sub-Saharan Africa (WB)' 'Sudan'
 'Suriname' 'Syria' 'Tajikistan' 'Tanzania' 'Thailand' 'Togo' 'Tonga'
 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Turkmenistan'
 'Turks and Caicos Islands' 'Tuvalu' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'Upper-middle-income countries' 'Uruguay'
 'Uzbekistan' 'Vanuatu' 'Venezuela' 'Vietnam' 'World' 'Yemen' 'Zambia'
 'Zimbabwe']
197

In [20]:
print(df_ip["entity"].unique())
print(df_ip["entity"].nunique())

['Afghanistan' 'Albania' 'Algeria' 'American Samoa' 'Andorra' 'Angola'
 'Anguilla' 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba'
 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh'
 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda' 'Bhutan'
 'Bolivia' 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'Brunei'
 'Bulgaria' 'Burkina Faso' 'Burundi' 'Cambodia' 'Cameroon' 'Canada'
 'Cape Verde' 'Cayman Islands' 'Central African Republic'
 'Central and Southern Asia (SDG)' 'Chad' 'Channel Islands' 'Chile'
 'China' 'Cocos Islands' 'Colombia' 'Comoros' 'Congo' 'Cook Islands'
 'Costa Rica' "Cote d'Ivoire" 'Croatia' 'Cuba' 'Cyprus' 'Czechoslovakia'
 'Democratic Republic of Congo' 'Denmark' 'Djibouti' 'Dominican Republic'
 'East Asia and Pacific (WB)' 'East Timor'
 'Eastern and South-Eastern Asia (SDG)' 'Ecuador' 'Egypt' 'El Salvador'
 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia'
 'Europe and Central Asia (WB)' 'Europe and Northern America (SDG)'
 'Falkland Islands' 'Faroe Islands' 'Fiji' 'Finland' 'France'
 'French Guiana' 'French Polynesia' 'Gabon' 'Gambia' 'Georgia' 'Germany'
 'Ghana' 'Gibraltar' 'Greece' 'Greenland' 'Grenada' 'Guadeloupe' 'Guam'
 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti' 'Honduras'
 'Hong Kong' 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran' 'Iraq'
 'Ireland' 'Isle of Man' 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jordan'
 'Kazakhstan' 'Kenya' 'Kiribati' 'Kuwait' 'Kyrgyzstan' 'Laos'
 'Latin America and Caribbean (WB)'
 'Latin America and the Caribbean (SDG)' 'Latvia' 'Lebanon' 'Lesotho'
 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania' 'Low-income countries'
 'Lower-middle-income countries' 'Luxembourg' 'Macao' 'Madagascar'
 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta' 'Marshall Islands'
 'Martinique' 'Mauritania' 'Mauritius' 'Mexico'
 'Middle East and North Africa (WB)' 'Middle-income countries' 'Moldova'
 'Monaco' 'Mongolia' 'Montenegro' 'Morocco' 'Mozambique' 'Myanmar'
 'Namibia' 'Nauru' 'Nepal' 'Netherlands' 'Netherlands Antilles'
 'New Caledonia' 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'Niue'
 'Norfolk Island' 'North America (WB)' 'North Korea' 'North Macedonia'
 'Northern Africa and Western Asia (SDG)' 'Norway'
 'Oceania (excluding Australia and New Zealand) (SDG)' 'Oman' 'Pakistan'
 'Palau' 'Palestine' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru'
 'Philippines' 'Poland' 'Portugal' 'Puerto Rico' 'Qatar' 'Reunion'
 'Romania' 'Russia' 'Rwanda' 'Saint Helena' 'Saint Pierre and Miquelon'
 'Saint Vincent and the Grenadines' 'Samoa' 'San Marino'
 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia' 'Seychelles'
 'Sierra Leone' 'Singapore' 'Slovenia' 'Solomon Islands' 'Somalia'
 'Somaliland' 'South Africa' 'South Asia (WB)' 'South Korea' 'South Sudan'
 'Spain' 'Sri Lanka' 'Sub-Saharan Africa (SDG)' 'Sub-Saharan Africa (WB)'
 'Sudan' 'Suriname' 'Sweden' 'Switzerland' 'Syria' 'Tajikistan' 'Tanzania'
 'Thailand' 'Togo' 'Tokelau' 'Tonga' 'Trinidad and Tobago' 'Tunisia'
 'Turkey' 'Turkmenistan' 'USSR' 'Uganda' 'Ukraine' 'United Arab Emirates'
 'United Kingdom' 'United States' 'United States Virgin Islands'
 'Upper-middle-income countries' 'Uruguay' 'Uzbekistan' 'Vanuatu'
 'Venezuela' 'Vietnam' 'Western Europe (Buringh and van Zanden)' 'World'
 'Yemen' 'Yugoslavia' 'Zambia' 'Zanzibar' 'Zimbabwe']
242

In [21]:
print(df_gc["entity"].unique())
print(df_gc["entity"].nunique())

['Afghanistan' 'Albania' 'Algeria' 'Andorra' 'Angola'
 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba' 'Australia' 'Austria'
 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus'
 'Belgium' 'Belize' 'Benin' 'Bermuda' 'Bhutan' 'Bolivia'
 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'Brunei' 'Bulgaria'
 'Burkina Faso' 'Burundi' 'Cambodia' 'Cameroon' 'Canada' 'Cape Verde'
 'Cayman Islands' 'Central African Republic' 'Chad' 'Chile' 'China'
 'Colombia' 'Comoros' 'Congo' 'Costa Rica' "Cote d'Ivoire" 'Croatia'
 'Curacao' 'Cyprus' 'Czechia' 'Democratic Republic of Congo' 'Denmark'
 'Djibouti' 'Dominica' 'Dominican Republic' 'East Asia and Pacific (WB)'
 'East Timor' 'Ecuador' 'Egypt' 'El Salvador' 'Equatorial Guinea'
 'Estonia' 'Eswatini' 'Ethiopia' 'Europe and Central Asia (WB)'
 'European Union (27)' 'Faroe Islands' 'Fiji' 'Finland' 'France' 'Gabon'
 'Gambia' 'Georgia' 'Germany' 'Ghana' 'Greece' 'Greenland' 'Grenada'
 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti'
 'High-income countries' 'Honduras' 'Hong Kong' 'Hungary' 'Iceland'
 'India' 'Indonesia' 'Iran' 'Iraq' 'Ireland' 'Israel' 'Italy' 'Jamaica'
 'Japan' 'Jordan' 'Kazakhstan' 'Kenya' 'Kiribati' 'Kosovo' 'Kuwait'
 'Kyrgyzstan' 'Laos' 'Latin America and Caribbean (WB)' 'Latvia' 'Lebanon'
 'Lesotho' 'Liberia' 'Libya' 'Lithuania' 'Low-income countries'
 'Lower-middle-income countries' 'Luxembourg' 'Macao' 'Madagascar'
 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta' 'Marshall Islands'
 'Mauritania' 'Mauritius' 'Mexico' 'Micronesia (country)'
 'Middle East, North Africa, Afghanistan and Pakistan (WB)' 'Moldova'
 'Mongolia' 'Montenegro' 'Morocco' 'Mozambique' 'Myanmar' 'Namibia'
 'Nauru' 'Nepal' 'Netherlands' 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria'
 'North America (WB)' 'North Macedonia' 'Norway' 'Oman' 'Pakistan' 'Palau'
 'Palestine' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines'
 'Poland' 'Portugal' 'Puerto Rico' 'Qatar' 'Romania' 'Russia' 'Rwanda'
 'Saint Kitts and Nevis' 'Saint Lucia' 'Saint Vincent and the Grenadines'
 'Samoa' 'San Marino' 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal'
 'Serbia' 'Seychelles' 'Sierra Leone' 'Singapore'
 'Sint Maarten (Dutch part)' 'Slovakia' 'Slovenia' 'Solomon Islands'
 'Somalia' 'South Africa' 'South Asia (WB)' 'South Korea' 'Spain'
 'Sri Lanka' 'Sub-Saharan Africa (WB)' 'Sudan' 'Suriname' 'Sweden'
 'Switzerland' 'Syria' 'Tajikistan' 'Tanzania' 'Thailand' 'Togo' 'Tonga'
 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Turkmenistan'
 'Turks and Caicos Islands' 'Tuvalu' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'United Kingdom' 'United States'
 'United States Virgin Islands' 'Upper-middle-income countries' 'Uruguay'
 'Uzbekistan' 'Vanuatu' 'Vietnam' 'World' 'Zambia' 'Zimbabwe']
212

In [22]:
print(df_ays["entity"].unique())
print(df_ays["entity"].nunique())

['Afghanistan' 'Africa' 'Albania' 'Algeria' 'American Samoa' 'Andorra'
 'Angola' 'Anguilla' 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba'
 'Asia' 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain'
 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda'
 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'Brunei'
 'Bulgaria' 'Burkina Faso' 'Burundi' 'Cambodia' 'Cameroon' 'Canada'
 'Cape Verde' 'Cayman Islands' 'Central African Republic'
 'Central and Southern Asia (SDG)' 'Chad' 'Channel Islands' 'Chile'
 'China' 'Cocos Islands' 'Colombia' 'Comoros' 'Congo' 'Cook Islands'
 'Costa Rica' "Cote d'Ivoire" 'Croatia' 'Cuba' 'Cyprus' 'Czechia'
 'Czechoslovakia' 'Democratic Republic of Congo' 'Denmark' 'Djibouti'
 'Dominican Republic' 'East Asia and Pacific (WB)' 'East Timor'
 'Eastern and South-Eastern Asia (SDG)' 'Ecuador' 'Egypt' 'El Salvador'
 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia' 'Europe'
 'Europe and Central Asia (WB)' 'Europe and Northern America (SDG)'
 'Falkland Islands' 'Faroe Islands' 'Fiji' 'Finland' 'France'
 'French Guiana' 'French Polynesia' 'Gabon' 'Gambia' 'Georgia' 'Germany'
 'Ghana' 'Gibraltar' 'Greece' 'Greenland' 'Grenada' 'Guadeloupe' 'Guam'
 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti' 'Honduras'
 'Hong Kong' 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran' 'Iraq'
 'Ireland' 'Isle of Man' 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jordan'
 'Kazakhstan' 'Kenya' 'Kiribati' 'Kuwait' 'Kyrgyzstan' 'Laos'
 'Latin America and Caribbean (WB)'
 'Latin America and the Caribbean (SDG)' 'Latvia' 'Lebanon' 'Lesotho'
 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania' 'Low-income countries'
 'Lower-middle-income countries' 'Luxembourg' 'Macao' 'Madagascar'
 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta' 'Marshall Islands'
 'Martinique' 'Mauritania' 'Mauritius' 'Mexico'
 'Middle East and North Africa (WB)' 'Middle-income countries' 'Moldova'
 'Monaco' 'Mongolia' 'Montenegro' 'Morocco' 'Mozambique' 'Myanmar'
 'Namibia' 'Nauru' 'Nepal' 'Netherlands' 'Netherlands Antilles'
 'New Caledonia' 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'Niue'
 'Norfolk Island' 'North America' 'North America (WB)' 'North Korea'
 'North Macedonia' 'Northern Africa and Western Asia (SDG)' 'Norway'
 'Oceania' 'Oceania (excluding Australia and New Zealand) (SDG)' 'Oman'
 'Pakistan' 'Palau' 'Palestine' 'Panama' 'Papua New Guinea' 'Paraguay'
 'Peru' 'Philippines' 'Poland' 'Portugal' 'Puerto Rico' 'Qatar' 'Reunion'
 'Romania' 'Russia' 'Rwanda' 'Saint Helena' 'Saint Pierre and Miquelon'
 'Saint Vincent and the Grenadines' 'Samoa' 'San Marino'
 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia' 'Seychelles'
 'Sierra Leone' 'Singapore' 'Slovakia' 'Slovenia' 'Solomon Islands'
 'Somalia' 'Somaliland' 'South Africa' 'South America' 'South Asia (WB)'
 'South Korea' 'South Sudan' 'Spain' 'Sri Lanka'
 'Sub-Saharan Africa (SDG)' 'Sub-Saharan Africa (WB)' 'Sudan' 'Suriname'
 'Sweden' 'Switzerland' 'Syria' 'Taiwan' 'Tajikistan' 'Tanzania'
 'Thailand' 'Togo' 'Tokelau' 'Tonga' 'Trinidad and Tobago' 'Tunisia'
 'Turkey' 'Turkmenistan' 'USSR' 'Uganda' 'Ukraine' 'United Arab Emirates'
 'United Kingdom' 'United States' 'United States Virgin Islands'
 'Upper-middle-income countries' 'Uruguay' 'Uzbekistan' 'Vanuatu'
 'Venezuela' 'Vietnam' 'Western Europe (Buringh and van Zanden)' 'Yemen'
 'Yugoslavia' 'Zambia' 'Zanzibar' 'Zimbabwe']
250

## Year Range

In [25]:
print(df_alr['year'].min())
print(df_alr['year'].max())

1970
2023

In [26]:
print(df_ylr['year'].min())
print(df_ylr['year'].max())

1970
2023

In [27]:
print(df_ip['year'].min())
print(df_ip['year'].max())

1475
2023

In [28]:
print(df_gc['year'].min())
print(df_gc['year'].max())

1990
2024

In [29]:
print(df_ays['year'].min())
print(df_ays['year'].max())

1475
2023

## Null % Summary

In [30]:
null_summary = pd.DataFrame({
    "Null Count": df_alr.isnull().sum(),
    "Null %": (df_alr.isnull().sum() / len(df_alr)) * 100
})

null_summary.sort_values("Null %", ascending=False)

                                                    Null Count    Null %
code                                                       729  42.26087
entity                                                       0   0.00000
year                                                         0   0.00000
adult_literacy_rate__population_15plus_years__b...           0   0.00000

In [31]:
null_summary = pd.DataFrame({
    "Null Count": df_ylr.isnull().sum(),
    "Null %": (df_ylr.isnull().sum() / len(df_ylr)) * 100
})

null_summary.sort_values("Null %", ascending=False)

                                                    Null Count     Null %
owid_region                                                791  39.510490
code                                                       742  37.062937
youth_literacy_rate__population_15_24_years__ma...          77   3.846154
entity                                                       0   0.000000
year                                                         0   0.000000
youth_literacy_rate__population_15_24_years__fe...           0   0.000000

In [32]:
null_summary = pd.DataFrame({
    "Null Count": df_ip.isnull().sum(),
    "Null %": (df_ip.isnull().sum() / len(df_ip)) * 100
})

null_summary.sort_values("Null %", ascending=False)

                 Null Count     Null %
code                    733  35.599806
entity                    0   0.000000
year                      0   0.000000
illiteracy_rate           0   0.000000
literacy_rate             0   0.000000

In [33]:
null_summary = pd.DataFrame({
    "Null Count": df_gc.isnull().sum(),
    "Null %": (df_gc.isnull().sum() / len(df_gc)) * 100
})

null_summary.sort_values("Null %", ascending=False)

                   Null Count   Null %
owid_region               455  6.28453
entity                      0  0.00000
code                        0  0.00000
year                        0  0.00000
ny_gdp_pcap_pp_kd           0  0.00000

In [34]:
null_summary = pd.DataFrame({
    "Null Count": df_ays.isnull().sum(),
    "Null %": (df_ays.isnull().sum() / len(df_ays)) * 100
})

null_summary.sort_values("Null %", ascending=False)

                                                    Null Count     Null %
literacy_rate                                             3365  62.721342
mf_youth_and_adults__15_64_years__average_years...        1697  31.630941
owid_region                                                893  16.644921
code                                                       890  16.589003
population_historical                                      605  11.276794
year                                                         0   0.000000
entity                                                       0   0.000000

## Duplicate Check

In [35]:
df_alr.duplicated().sum()

np.int64(0)

In [36]:
df_ylr.duplicated().sum()

np.int64(0)

In [37]:
df_ip.duplicated().sum()

np.int64(0)

In [38]:
df_gc.duplicated().sum()

np.int64(0)

In [39]:
df_ays.duplicated().sum()

np.int64(0)

# Initial Merging Strategy

## Creating df_literacy

In [41]:
df_literacy = pd.merge(df_alr, df_ylr, on = ['entity', 'code', 'year'], how = 'outer')
print(df_literacy.shape)
print(df_literacy.head())

(2019, 7)
        entity code  year  \
0  Afghanistan  AFG  1979
1  Afghanistan  AFG  2011
2  Afghanistan  AFG  2015
3  Afghanistan  AFG  2021
4  Afghanistan  AFG  2022

   adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99  \
0                                           18.00000
1                                           31.00000
2                                           33.75384
3                                           37.00000
4                                                NaN

   youth_literacy_rate__population_15_24_years__male__pct__lr_ag15t24_m  \
0                                           46.00000
1                                           62.00000
2                                           57.73505
3                                           71.00000
4                                           83.40000

   youth_literacy_rate__population_15_24_years__female__pct__lr_ag15t24_f  \
0                                           11.00000
1                                           32.00000
2                                           25.48416
3                                           42.00000
4                                           44.17171

  owid_region
0        Asia
1        Asia
2        Asia
3        Asia
4        Asia

In [43]:
df_literacy.to_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\data\raw\df_literacy.csv")

## Creating df_illiteracy

In [42]:
df_illiteracy = df_ip.copy()
print(df_illiteracy.shape)
print(df_illiteracy.head())

(2059, 5)
        entity code  year  illiteracy_rate  literacy_rate
0  Afghanistan  AFG  1950        97.000000        3.00000
1  Afghanistan  AFG  1979        82.000000       18.00000
2  Afghanistan  AFG  2011        69.000000       31.00000
3  Afghanistan  AFG  2015        66.246155       33.75384
4  Afghanistan  AFG  2021        63.000000       37.00000

In [44]:
df_illiteracy.to_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\data\raw\df_illiteracy.csv")

## Create df_gdp_schooling

In [45]:
df_gdp_schooling = pd.merge(df_gc, df_ays, on = ['entity', 'code', 'year', 'owid_region'], how = 'outer')
print(df_gdp_schooling.shape)
print(df_gdp_schooling.head())

(11113, 8)
        entity code  year  ny_gdp_pcap_pp_kd owid_region  literacy_rate  \
0  Afghanistan  AFG  1870                NaN        Asia            NaN
1  Afghanistan  AFG  1875                NaN        Asia            NaN
2  Afghanistan  AFG  1880                NaN        Asia            NaN
3  Afghanistan  AFG  1885                NaN        Asia            NaN
4  Afghanistan  AFG  1890                NaN        Asia            NaN

   mf_youth_and_adults__15_64_years__average_years_of_education  \
0                                               0.01
1                                               0.01
2                                               0.01
3                                               0.01
4                                               0.01

   population_historical
0              4101170.0
1              4193635.0
2              4288021.0
3              4384343.0
4              4482635.0

In [46]:
df_gdp_schooling.to_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\data\raw\df_gdp_schooling.csv")