In [1]:
import pandas as pd
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

In [2]:
df1 = pd.read_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\data\processed\df_literacy.csv", index_col = 0)
df2 = pd.read_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\data\processed\df_illiteracy.csv", index_col = 0)
df3 = pd.read_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\data\processed\df_gdp_schooling.csv", index_col = 0)

In [3]:
df1.drop(columns = ["invalid_literacy_flag", "adult_literacy_rate_outlier_flag", "youth_literacy_rate_M_outlier_flag", "youth_literacy_rate_F_outlier_flag"], axis = 1, inplace = True)
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1103 entries, 1 to 2018
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   country                1103 non-null   object
 1   code                   1103 non-null   object
 2   year                   1103 non-null   int64
 3   adult_literacy_rate    1103 non-null   float64
 4   youth_literacy_rate_M  1103 non-null   float64
 5   youth_literacy_rate_F  1103 non-null   float64
 6   continent              1103 non-null   object
dtypes: float64(3), int64(1), object(3)
memory usage: 68.9+ KB

In [4]:
df2.drop(columns = ["invalid_literacy_flag", "literacy_rate_outlier_flag", "illiteracy_rate_outlier_flag"], axis = 1, inplace = True)
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 833 entries, 2 to 2058
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country          833 non-null    object
 1   code             833 non-null    object
 2   year             833 non-null    int64
 3   illiteracy_rate  833 non-null    float64
 4   literacy_rate    833 non-null    float64
dtypes: float64(2), int64(1), object(2)
memory usage: 39.0+ KB

In [5]:
df3.drop(columns = ["invalid_gdp_flag", "invalid_schooling_flag", "log_gdp", "log_gdp_zscore", "gdp_outlier_flag"], axis = 1, inplace = True)
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4963 entries, 25 to 11112
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              4963 non-null   object
 1   code                 4963 non-null   object
 2   year                 4963 non-null   int64
 3   gdp                  4919 non-null   float64
 4   continent            4963 non-null   object
 5   avg_schooling_years  4963 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 271.4+ KB

# Connect to MYSQL

In [6]:
password = quote_plus("*********")
bridge = create_engine(f"mysql+pymysql://root:{password}@localhost:3306/global_literacy_analysis")
bridge

Engine(mysql+pymysql://root:***@localhost:3306/global_literacy_analysis)

# Create Tables with Keys & Values

## Literacy Rates Table

In [24]:
with bridge.connect() as conn:
    conn.execute(text("""CREATE TABLE literacy_rates (
                        country VARCHAR(100) NOT NULL,
                        code VARCHAR(10),
                        year INT NOT NULL,
                        adult_literacy_rate DOUBLE,
                        youth_literacy_rate_M DOUBLE,
                        youth_literacy_rate_F DOUBLE,
                        continent VARCHAR(50),
                        PRIMARY KEY (country, year)
                    );
                    """))

In [25]:
df1.to_sql(name = "literacy_rates", con = bridge, if_exists = "append", index = False)

1103

In [7]:
pd.read_sql("describe literacy_rates", bridge)

                   Field          Type Null  Key Default Extra
0                country  varchar(100)   NO  PRI    None
1                   code   varchar(10)  YES         None
2                   year           int   NO  PRI    None
3    adult_literacy_rate        double  YES         None
4  youth_literacy_rate_M        double  YES         None
5  youth_literacy_rate_F        double  YES         None
6              continent   varchar(50)  YES         None

## Illiteracy Population

In [30]:
with bridge.connect() as conn:
    conn.execute(text("""create table illiteracy_population (
                        country varchar(100) not null,
                        code varchar(10),
                        year int not null,
                        illiteracy_rate double,
                        literacy_rate double,
                        primary key (country, year)
                        );
                        """))

In [31]:
df2.to_sql(name = "illiteracy_population", con = bridge, if_exists = "append", index = False)

833

In [8]:
pd.read_sql("describe illiteracy_population", bridge)

             Field          Type Null  Key Default Extra
0          country  varchar(100)   NO  PRI    None
1             code   varchar(10)  YES         None
2             year           int   NO  PRI    None
3  illiteracy_rate        double  YES         None
4    literacy_rate        double  YES         None

## GDP_Schooling

In [37]:
with bridge.connect() as conn:
    conn.execute(text("""create table gdp_schooling (
                        country varchar(100) not null,
                        code varchar(10),
                        year int not null,
                        gdp double,
                        continent varchar(50),
                        avg_schooling_years double,
                        primary key (country, year)
                        );
                        """))

In [38]:
df3.to_sql(name = "gdp_schooling", con = bridge, if_exists = "append", index = False)

4963

In [9]:
pd.read_sql("describe gdp_schooling", bridge)

                 Field          Type Null  Key Default Extra
0              country  varchar(100)   NO  PRI    None
1                 code   varchar(10)  YES         None
2                 year           int   NO  PRI    None
3                  gdp        double  YES         None
4            continent   varchar(50)  YES         None
5  avg_schooling_years        double  YES         None

# Literacy_Rate Queries

### Get top 5 countries with highest adult literacy in 2020.

In [10]:
df_Q1 = pd.read_sql("""select * from literacy_rates
                        where year = 2020
                        order by adult_literacy_rate desc
                        limit 5;"""
                    , bridge)
df_Q1

,country,code,year,adult_literacy_rate,youth_literacy_rate_M,youth_literacy_rate_F,continent
0,Armenia,ARM,2020,100.0,100.0,100.0,Asia
1,Mongolia,MNG,2020,99.0,99.0,99.0,Asia
2,Spain,ESP,2020,99.0,99.0,100.0,Europe
3,Palestine,PSE,2020,98.0,99.0,99.0,Asia
4,Saudi Arabia,SAU,2020,98.0,100.0,99.0,Asia

In [11]:
df_Q1.to_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\powerbi\SQL_database\Q1.csv")

### Find countries where female youth literacy < 80%.

In [13]:
df_Q2 = pd.read_sql("""select * from literacy_rates
                        where youth_literacy_rate_F < 80;""",
                    bridge)
df_Q2

,country,code,year,adult_literacy_rate,youth_literacy_rate_M,youth_literacy_rate_F,continent
0,Afghanistan,AFG,2011,31.00000,62.00000,32.00000,Asia
1,Afghanistan,AFG,2015,33.75384,57.73505,25.48416,Asia
2,Afghanistan,AFG,2021,37.00000,71.00000,42.00000,Asia
3,Afghanistan,AFG,2022,37.00000,83.40000,44.17171,Asia
4,Angola,AGO,2001,67.00000,84.00000,63.00000,Africa
...,...,...,...,...,...,...,...
240,Yemen,YEM,2023,37.00000,61.76000,76.91698,Asia
241,Zambia,ZMB,1990,65.00000,67.00000,66.00000,Africa
242,Zambia,ZMB,1999,68.00000,73.00000,66.00000,Africa
243,Zambia,ZMB,2002,69.00000,78.00000,66.00000,Africa
244,Zambia,ZMB,2018,71.13230,82.44786,72.90992,Africa

In [14]:
df_Q2.to_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\powerbi\SQL_database\Q2.csv")

### Average adult literacy per continent (owid region).

In [15]:
df_Q3 = pd.read_sql("""select continent,
                        round(avg(adult_literacy_rate), 2) as avg_adult_literacy
                        from literacy_rates
                        group by continent
                        order by avg_adult_literacy desc;""",
                    bridge)
df_Q3

       continent  avg_adult_literacy
0         Europe               97.45
1  South America               93.10
2        Oceania               92.42
3  North America               87.50
4           Asia               85.97
5         Africa               60.94

In [16]:
df_Q3.to_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\powerbi\SQL_database\Q3.csv")

# Illiteracy_Population Queries

###  Countries with illiteracy % > 20% in 2000.

In [17]:
df_Q4 = pd.read_sql("""select * from illiteracy_population
                        where illiteracy_rate > 20
                        and year = 2020;""",
                    bridge)
df_Q4

      country code  year  illiteracy_rate  literacy_rate
0  Bangladesh  BGD  2020        25.000000       75.00000
1      Malawi  MWI  2020        29.847733       70.15227
2  Mauritania  MRT  2020        40.470340       59.52966
3  Mozambique  MOZ  2020        40.000000       60.00000

In [18]:
df_Q4.to_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\powerbi\SQL_database\Q4.csv")

###  Trend of illiteracy % for India (2000–2020).

In [19]:
df_Q5 = pd.read_sql("""select year, illiteracy_rate from illiteracy_population
                        where country = "India"
                        and year between 2000 and 2020
                        order by year asc;""",
                    bridge)
df_Q5

   year  illiteracy_rate
0  2001             39.0
1  2006             37.0
2  2011             31.0

In [20]:
df_Q5.to_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\powerbi\SQL_database\Q5.csv")

### Top 10 countries with largest illiterate population in the last year.

In [21]:
df_Q6 = pd.read_sql("""select * from illiteracy_population
                        where year = (select max(year) from illiteracy_population)
                        order by illiteracy_rate desc
                        limit 10;""",
                    bridge)
df_Q6

                country code  year  illiteracy_rate  literacy_rate
0               Senegal  SEN  2023        49.644180       50.35582
1                 India  IND  2023        18.000000       82.00000
2               Tunisia  TUN  2023        13.753181       86.24682
3               Vanuatu  VUT  2023        12.039680       87.96032
4           El Salvador  SLV  2023        10.000000       90.00000
5             Sri Lanka  LKA  2023         7.000000       93.00000
6                Jordan  JOR  2023         5.000000       95.00000
7                 Nauru  NRU  2023         3.413460       96.58654
8               Bahrain  BHR  2023         2.000000       98.00000
9  United Arab Emirates  ARE  2023         2.000000       98.00000

In [22]:
df_Q6.to_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\powerbi\SQL_database\Q6.csv")

# GDP_Schooling Queries

### Find countries with avg_years_schooling > 7 and gdp_per_capita < 5000.

In [23]:
df_Q7 = pd.read_sql("""select * from gdp_schooling
                        where avg_schooling_years > 7
                        and gdp < 5000
                        order by avg_schooling_years desc;""",
                    bridge)
df_Q7

        country code  year        gdp continent  avg_schooling_years
0         Tonga  TON  1990  4487.8193   Oceania               11.220
1         Tonga  TON  1991  4766.3880   Oceania               11.220
2         Tonga  TON  1992  4772.3310   Oceania               11.220
3         Tonga  TON  1993  4946.7180   Oceania               11.220
4    Kyrgyzstan  KGZ  1992  4701.9910      Asia               11.050
..          ...  ...   ...        ...       ...                  ...
171    Cameroon  CMR  2015  4698.6670    Africa                7.050
172     Lesotho  LSO  2004  2178.6648    Africa                7.042
173       Ghana  GHA  2003  3507.7510    Africa                7.036
174       China  CHN  1994  2556.6406      Asia                7.026
175        Togo  TGO  2016  2427.3003    Africa                7.016

[176 rows x 6 columns]

In [24]:
df_Q7.to_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\powerbi\SQL_database\Q7.csv")

### Rank countries by GDP per capita for the year 2020.

In [26]:
df_Q8 = pd.read_sql("""select *,
                        dense_rank() over (order by gdp desc)
                        as gdp_rank
                        from gdp_schooling
                        where year = 2020;""",
                    bridge)
df_Q8

,country,code,year,gdp,continent,avg_schooling_years,gdp_rank
0,Luxembourg,LUX,2020,129865.630,Europe,11.53,1
1,Singapore,SGP,2020,115893.040,Asia,13.06,2
2,Qatar,QAT,2020,103061.900,Asia,8.52,3
3,Ireland,IRL,2020,101968.555,Europe,13.74,4
4,Norway,NOR,2020,86096.055,Europe,12.08,5
...,...,...,...,...,...,...,...
141,Cuba,CUB,2020,NaN,North America,11.61,142
142,Reunion,REU,2020,NaN,Africa,8.71,142
143,Taiwan,TWN,2020,NaN,Asia,12.76,142
144,Venezuela,VEN,2020,NaN,South America,9.33,142
145,Yemen,YEM,2020,NaN,Asia,5.56,142

In [27]:
df_Q8.to_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\powerbi\SQL_database\Q8.csv")

### Find global average schooling years per year.

In [29]:
df_Q9 = pd.read_sql("""select year,
                        round(avg(avg_schooling_years), 2) as global_schooling_avg
                        from gdp_schooling
                        group by year
                        order by year asc""",
                    bridge)
df_Q9

    year  global_schooling_avg
0   1990                  7.27
1   1991                  7.41
2   1992                  7.49
3   1993                  7.56
4   1994                  7.60
5   1995                  7.66
6   1996                  7.79
7   1997                  7.86
8   1998                  7.93
9   1999                  7.99
10  2000                  8.01
11  2001                  8.10
12  2002                  8.20
13  2003                  8.26
14  2004                  8.34
15  2005                  8.41
16  2006                  8.49
17  2007                  8.55
18  2008                  8.62
19  2009                  8.69
20  2010                  8.76
21  2011                  8.80
22  2012                  8.86
23  2013                  8.89
24  2014                  8.94
25  2015                  8.99
26  2016                  9.05
27  2017                  9.13
28  2018                  9.20
29  2019                  9.28
30  2020                  9.35
31  2021                  9.34
32  2022                  9.34
33  2023                  9.35
34  2024                  9.36

In [30]:
df_Q9.to_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\powerbi\SQL_database\Q9.csv")

# Join Queries

### List top 10 countries in 2020 with highest GDP per capita but lowest average years of schooling(less than 6).

In [32]:
df_Q10 = pd.read_sql("""select country, gdp, avg_schooling_years
                        from gdp_schooling
                        where year = 2020
                        and avg_schooling_years < 6
                        order by gdp desc
                        limit 10""",
                     bridge)
df_Q10

            country        gdp  avg_schooling_years
0          Cambodia  6128.7820                 5.81
1        Mauritania  5963.2354                 5.55
2  Papua New Guinea  4077.6313                 4.84
3           Senegal  4018.0413                 4.40
4             Sudan  3401.2498                 4.38
5             Haiti  3239.8354                 5.95
6              Mali  2796.4104                 3.55
7       Afghanistan  2769.6858                 5.69
8      Sierra Leone  2752.6262                 4.99
9            Gambia  2702.3190                 4.92

In [33]:
df_Q10.to_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\powerbi\SQL_database\Q10.csv")

###  Show countries where the illiterate population is high despite having more than 10 average years of schooling.

In [35]:
df_Q11 = pd.read_sql("""select g.country, g.avg_schooling_years, i.illiteracy_rate
                        from gdp_schooling g inner join illiteracy_population i
                        on g.country = i.country
                        and g.year = i.year
                        and g.avg_schooling_years > 10
                        and i.illiteracy_rate > 10
                        order by i.illiteracy_rate desc;""",
                     bridge)
df_Q11

        country  avg_schooling_years  illiteracy_rate
0      Botswana               10.270        31.000000
1      Botswana               10.270        19.000000
2  South Africa               10.278        13.000000
3         Malta               10.060        12.000000
4         Gabon               10.180        11.141663
5     Singapore               12.540        11.000000

In [36]:
df_Q11.to_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\powerbi\SQL_database\Q11.csv")

### Compare literacy rates and GDP per capita growth for a selected country over the last 20 years. (country of your choice)

In [41]:
df_Q12 = pd.read_sql("""SELECT g.year, i.literacy_rate, g.gdp
                        AS gdp_per_capita,
                        ROUND(((g.gdp - LAG(g.gdp) OVER (ORDER BY g.year)) / LAG(g.gdp) OVER (ORDER BY g.year)) * 100, 2)
                        AS gdp_growth_percent
                        FROM gdp_schooling g JOIN illiteracy_population i
                        ON g.country = i.country
                        AND g.year = i.year
                        WHERE g.country = 'India'
                        AND g.year >= (SELECT MAX(year) - 20 FROM gdp_schooling)
                        ORDER BY g.year;""",
                    bridge)
df_Q12

   year  literacy_rate  gdp_per_capita  gdp_growth_percent
0  2006           63.0       4129.7783                 NaN
1  2011           69.0       5249.5493               27.11
2  2022           76.0       8594.3920               63.72
3  2023           82.0       9301.7560                8.23

In [42]:
df_Q12.to_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\powerbi\SQL_database\Q12.csv")

###  Show the difference between youth literacy male and female rates for countries with GDP per capita above $30,000 in 2020.

In [44]:
df_Q13 = pd.read_sql("""SELECT s.country, s.gdp AS gdp_per_capita, l.youth_literacy_rate_M, l.youth_literacy_rate_F,
                        ROUND(l.youth_literacy_rate_M - l.youth_literacy_rate_F, 2) AS gender_gap
                        FROM gdp_schooling s JOIN literacy_rates l
                        ON s.country = l.country
                        AND s.year = l.year
                        WHERE s.year = 2020
                        AND s.gdp > 30000
                        ORDER BY gender_gap DESC;""",
                    bridge)
df_Q13

,country,gdp_per_capita,youth_literacy_rate_M,youth_literacy_rate_F,gender_gap
0,Saudi Arabia,57420.734,100.0,99.0,1.0
1,Singapore,115893.040,100.0,100.0,0.0
2,Kuwait,49372.820,99.0,100.0,-1.0
3,Spain,41553.450,99.0,100.0,-1.0

In [45]:
df_Q13.to_csv(r"F:\DATA SCIENCE\Projects\Global Literacy & Educational Trends\powerbi\SQL_database\Q13.csv")